[package]
name = "stylus-writing"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
leptess = "0.14.0"
log = "0.4.29"
oar-ocr = "0.2.2"
rdev = "0.5.3"
sdl3 = "0.16.2"
simple-logging = "2.0.2"
taffy = "0.9.2"
